In [8]:
my_list = ["45.4","44.2","36.8","35.1","39.0","60.0","47.4","41.1","45.8","35.6"]

In [9]:
my_list[4]

'39.0'

In [11]:

my_list.append("55.2")
my_list

['45.4',
 '44.2',
 '36.8',
 '35.1',
 '39.0',
 '60.0',
 '47.4',
 '41.1',
 '45.8',
 '35.6',
 '55.2',
 '55.2']

In [12]:

del my_list[5]

my_list

['45.4',
 '44.2',
 '36.8',
 '35.1',
 '39.0',
 '47.4',
 '41.1',
 '45.8',
 '35.6',
 '55.2',
 '55.2']

In [13]:

x=0
for i in my_list: 
	if my_list[x] > "45":
		print(my_list[x])
		x=x + 1
	else:
		x=x + 1

45.4
47.4
45.8
55.2
55.2

In [14]:

import numpy
my_list2 = numpy.array([45.4,44.2,36.8,35.1,39.0,60.0,47.4,41.1,45.8,35.6])
my_list2

array([ 45.4,  44.2,  36.8,  35.1,  39. ,  60. ,  47.4,  41.1,  45.8,  35.6])

In [17]:
numpy.mean(my_list2)

43.040000000000006

In [18]:
numpy.std(my_list2)

7.0611897014596625

In [19]:
x=0
comp= float("45")
for i in my_list2: 
	if my_list2[x] < comp:
		print(my_list2[x])
		x=x + 1
	else:
		x=x + 1

44.2
36.8
35.1
39.0
41.1
35.6

In [20]:
numpy.max(my_list2)

60.0

In [21]:
numpy.min(my_list2)

35.100000000000001

In [29]:
import pandas
iris = pandas.read_csv("d:/Users/Aaron/Documents/School/SMU/Intro_To_DataScience/unit_11/Iris.csv")

In [30]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [37]:
help(pandas.DataFrame.drop)

Help on function drop in module pandas.core.generic:

drop(self, labels, axis=0, level=None, inplace=False, errors='raise')
    Return new object with labels in requested axis removed.

    Parameters
    ----------
    labels : single label or list-like
    axis : int or axis name
    level : int or level name, default None
        For MultiIndex
    inplace : bool, default False
        If True, do operation inplace and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and existing labels are dropped.

        .. versionadded:: 0.16.1

    Returns
    -------
    dropped : type of caller

In [46]:
iris.drop('Id',axis=1)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
5              5.4           3.9            1.7           0.4     Iris-setosa
6              4.6           3.4            1.4           0.3     Iris-setosa
7              5.0           3.4            1.5           0.2     Iris-setosa
8              4.4           2.9            1.4           0.2     Iris-setosa
9              4.9           3.1            1.5           0.1     Iris-setosa
10             5.4           3.7            1.5           0.2     Iris-setosa
11             4.8           3.4            1.6           0.2     Iris-setosa
12             4.8           3.0            1.4           0.1     Iris-setosa
13             4.3           3.0            1.1           0.1     Iris-setosa
14             5.8           4.0            1.2           0.2     Iris-setosa
15             5.7           4.4            1.5           0.4     Iris-setosa
16             5.4           3.9            1.3           0.4     Iris-setosa
17             5.1           3.5            1.4           0.3     Iris-setosa
18             5.7           3.8            1.7           0.3     Iris-setosa
19             5.1           3.8            1.5           0.3     Iris-setosa
20             5.4           3.4            1.7           0.2     Iris-setosa
21             5.1           3.7            1.5           0.4     Iris-setosa
22             4.6           3.6            1.0           0.2     Iris-setosa
23             5.1           3.3            1.7           0.5     Iris-setosa
24             4.8           3.4            1.9           0.2     Iris-setosa
25             5.0           3.0            1.6           0.2     Iris-setosa
26             5.0           3.4            1.6           0.4     Iris-setosa
27             5.2           3.5            1.5           0.2     Iris-setosa
28             5.2           3.4            1.4           0.2     Iris-setosa
29             4.7           3.2            1.6           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
120            6.9           3.2            5.7           2.3  Iris-virginica
121            5.6           2.8            4.9           2.0  Iris-virginica
122            7.7           2.8            6.7           2.0  Iris-virginica
123            6.3           2.7            4.9           1.8  Iris-virginica
124            6.7           3.3            5.7           2.1  Iris-virginica
125            7.2           3.2            6.0           1.8  Iris-virginica
126            6.2           2.8            4.8           1.8  Iris-virginica
127            6.1           3.0            4.9           1.8  Iris-virginica
128            6.4           2.8            5.6           2.1  Iris-virginica
129            7.2           3.0            5.8           1.6  Iris-virginica
130            7.4           2.8            6.1           1.9  Iris-virginica
131            7.9           3.8            6.4           2.0  Iris-virginica
132            6.4           2.8            5.6           2.2  Iris-virginica
133            6.3           2.8            5.1           1.5  Iris-virginica
134            6.1           2.6            5.6           1.4  Iris-virginica
135            7.7           3.0            6.1           2.3  Iris-virginica
136            6.3           3.4            5.6           2.4  Iris-virginica
137            6.4           3.1            5.5           1.8  Iris-virginica
138            6.0           3.0            4.8           1.8  Iris-virginica
139            6.9           3.1            5.4           2.1  Iris-virginica
140            6.7           3.1            5.6           2.4  Iris-virginica
141            6.9           3.1            5.1           2.3  Iris-virginica
142            5.8           2.7            5.1           1.9  Iris-virginica
143            6.8           3.2            5.9           2.3  Iris-virginica
144            6.7           3.3            5.7           2.5  Iris-virginica
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [49]:
setosa = iris[iris['Species'] == 'Iris-setosa']
setosa.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [51]:
setosa.describe()
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [52]:
iris.groupby('Species').describe()

                              Id  PetalLengthCm  PetalWidthCm  SepalLengthCm  \
Species
Iris-setosa     count   50.00000      50.000000     50.000000      50.000000
                mean    25.50000       1.464000      0.244000       5.006000
                std     14.57738       0.173511      0.107210       0.352490
                min      1.00000       1.000000      0.100000       4.300000
                25%     13.25000       1.400000      0.200000       4.800000
                50%     25.50000       1.500000      0.200000       5.000000
                75%     37.75000       1.575000      0.300000       5.200000
                max     50.00000       1.900000      0.600000       5.800000
Iris-versicolor count   50.00000      50.000000     50.000000      50.000000
                mean    75.50000       4.260000      1.326000       5.936000
                std     14.57738       0.469911      0.197753       0.516171
                min     51.00000       3.000000      1.000000       4.900000
                25%     63.25000       4.000000      1.200000       5.600000
                50%     75.50000       4.350000      1.300000       5.900000
                75%     87.75000       4.600000      1.500000       6.300000
                max    100.00000       5.100000      1.800000       7.000000
Iris-virginica  count   50.00000      50.000000     50.000000      50.000000
                mean   125.50000       5.552000      2.026000       6.588000
                std     14.57738       0.551895      0.274650       0.635880
                min    101.00000       4.500000      1.400000       4.900000
                25%    113.25000       5.100000      1.800000       6.225000
                50%    125.50000       5.550000      2.000000       6.500000
                75%    137.75000       5.875000      2.300000       6.900000
                max    150.00000       6.900000      2.500000       7.900000

                       SepalWidthCm
Species
Iris-setosa     count     50.000000
                mean       3.418000
                std        0.381024
                min        2.300000
                25%        3.125000
                50%        3.400000
                75%        3.675000
                max        4.400000
Iris-versicolor count     50.000000
                mean       2.770000
                std        0.313798
                min        2.000000
                25%        2.525000
                50%        2.800000
                75%        3.000000
                max        3.400000
Iris-virginica  count     50.000000
                mean       2.974000
                std        0.322497
                min        2.200000
                25%        2.800000
                50%        3.000000
                75%        3.175000
                max        3.800000

In [55]:
iris.groupby('Species').boxplot()

Iris-setosa             Axes(0.1,0.559091;0.363636x0.340909)
Iris-versicolor    Axes(0.536364,0.559091;0.363636x0.340909)
Iris-virginica              Axes(0.1,0.15;0.363636x0.340909)
dtype: object

In [57]:
help(iris.boxplot)

Help on method boxplot in module pandas.core.frame:

boxplot(column=None, by=None, ax=None, fontsize=None, rot=0, grid=True, figsize=None, layout=None, return_type=None, **kwds) method of pandas.core.frame.DataFrame instance
    Make a box plot from DataFrame column optionally grouped by some columns or
    other inputs

    Parameters
    ----------
    data : the pandas object holding the data
    column : column name or list of names, or vector
        Can be any valid input to groupby
    by : string or sequence
        Column in the DataFrame to group by
    ax : Matplotlib axes object, optional
    fontsize : int or string
    rot : label rotation angle
    figsize : A tuple (width, height) in inches
    grid : Setting this to True will show the grid
    layout : tuple (optional)
        (rows, columns) for the layout of the plot
    return_type : {None, 'axes', 'dict', 'both'}, default None
        The kind of object to return. The default is ``axes``
        'axes' returns the matplotlib axes the boxplot is drawn on;
        'dict' returns a dictionary  whose values are the matplotlib
        Lines of the boxplot;
        'both' returns a namedtuple with the axes and dict.

        When grouping with ``by``, a Series mapping columns to ``return_type``
        is returned, unless ``return_type`` is None, in which case a NumPy
        array of axes is returned with the same shape as ``layout``.
        See the prose documentation for more.

    kwds : other plotting keyword arguments to be passed to matplotlib boxplot
           function

    Returns
    -------
    lines : dict
    ax : matplotlib Axes
    (ax, lines): namedtuple

    Notes
    -----
    Use ``return_type='dict'`` when you want to tweak the appearance
    of the lines after plotting. In this case a dict containing the Lines
    making up the boxes, caps, fliers, medians, and whiskers is returned.

In [64]:
import seaborn as sns

In [65]:
sns.pairplot(iris,hue='Species')